### ISSUE TITLE
App versions above 5.0 not fully supported

### ISSUE THREAD

**Issue by ViktorVoloshko** [Mrakovic-ORG/NetLimiter_Patcher#3]
Testing versions 5.0 are crashing when trying to open About window. Not crucial if patch works (in educational purposes of course) but I'm not sure and don't know how to check that.

**Comment by 0x11DFE** [comment]
> Testing versions 5.0 are crashing when trying to open About window. Not crucial if patch works (in educational purposes of course) but I'm not sure and don't know how to check that.

This version is still in beta the problem is due to the LicenseType, They changed from int to string as the return type.

**Comment by 0x11DFE** [comment]
The issue was fixed. Please try the latest release. If you still got the same issue, re-open the issue.

**Comment by ViktorVoloshko** [comment]
Everything seems working perfect now, thx!
