### ISSUE TITLE
Virusscanners report this as a Virus

### ISSUE THREAD

**Issue by ghost** [Mrakovic-ORG/NetLimiter_Patcher#5]
Microsoft says its a RAT and Virustotal also has 35 Positives.
https://www.virustotal.com/gui/file/f0e6606c8c04ca6377c92d17c0622edb521a13c8689bc3568cef29c97b09327e

**Comment by 0x11DFE** [comment]
False positives, you can clearly see generic virus names in bad brands and no detections within Kaspersky or other better av's..
